name: ai_python_3_9
dependencies:
  - python=3.9
  - numpy
  - ipykernel
  - pandas
# Packages installed:
# /opt/conda/lib/python3.9/site-packages/numpy
# /opt/conda/lib/python3.9/site-packages/ipykernel
# /opt/conda/lib/python3.9/site-packages/pandas